### ISSUE TITLE
Download link unavailable!

### ISSUE THREAD

**Issue by Holim0711** [kuanghuei/Food-101N#1]
Dear Dr. Lee

I’m a student and interested in classification on noisy data.

I would like to download Food-101 and Food-101N datasets!

I tried at the download page(https://kuanghuei.github.io/Food-101N/) but it doesn’t seem to be working now…

I would appreciate it if you could open the new download link!

Thank you for your time and works!

**Comment by kuanghuei** [comment]
I will attempt to find another place to host the dataset by next month. Sorry for the inconvenience.

**Comment by Holim0711** [comment]
Thank you! It would be great!

**Comment by kuanghuei** [comment]
The data link has been restored.
