### ISSUE TITLE
Dataset url unavailable

### ISSUE THREAD

**Issue by smuelpeng** [kuanghuei/Food-101N#2]
Hello, @kuanghuei 
Thanks for your effort on noisy label learning!
I notice that the url( https://iudata.blob.core.windows.net/food101/Food-101N_release.zip ) of Food-101N has expired.
I am wondering if you could kindly update the dataset and necessary information about it. 

Thanks!

**Comment by kuanghuei** [comment]
The data link has been restored at the end of last year. Please let me know if you have further questions.
